line-length = 120
target-version = "py312"
lint.select = [
    "ALL", # include all the rules, including new ones
]
lint.ignore = [
    #### specific rules
    "ANN204", # missing return type
    "B904", # nested exceptions
    "D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",
    "EM101", # exception message literal
    "EM102", # exception message f-literal
    "FIX002", # fix TODOs
    "UP007", # type annotations
    "TD002", # TODOs
    "TD003", # TODOs
    "TRY003", # long exception messages
]