line-length = 120
target-version = "py312"
lint.select = [
    "ALL", # include all the rules, including new ones
]
lint.ignore = [
    #### specific rules
    "ANN201", # missing return type
    "ANN202", # missing return type
    "ANN204", # missing return type
    "ANN205", # missing return type
    "ANN206", # missing return type
    "B904", # nested exceptions
    "D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",
    "DTZ007", # datetime timezone
    "E741", # ambiguous variable name
    "EM101", # exception message literal
    "EM102", # exception message f-literal
    "FBT001", # bool function argument
    "FBT002", # bool function argument
    "FBT003", # bool function argument
    "FIX002", # fix TODOs
    "N802", # function name in lowercase
    "PERF401", # list extend
    "PIE790", # pass
    "PLR0913", # too many arguments
    "PLR2004", # magic numbers
    "UP007", # type annotations
    "S101", # assert
    "TC001", # type checking block
    "TD002", # TODOs
    "TD003", # TODOs
    "TRY003", # long exception messages
]